### ISSUE TITLE
Allow to configure drivers inside the sandbox (eg using SANE_CONFIG_DIR)

### ISSUE THREAD

**Issue by mbugni** [flathub/org.kde.skanlite#14]
As I mentioned in [this issue](https://github.com/flathub/org.kde.skanlite/issues/3#issuecomment-2298647550) it needs to set up the SANE_CONFIG_DIR environment variable in order to allow users to configure drivers in the sandbox.

My suggestion is `SANE_CONFIG_DIR="$XDG_CONFIG_HOME/sane.d:"`. Users can create the `$HOME/.var/app/org.kde.skanlite/config/sane.d` folder and add all required config file there.
Otherwise, it will not be possible to configure any driver, such as the `net` one.

Maybe, a similar approach can be hardcoded at build time. Otherwise, a wrapper launcher could be added, and the desktop file must be patched.

**Comment by travier** [comment]
Doing a wrapper to setup the right environment variables looks good to me.

**Comment by Erick555** [comment]
I think it should work even without a wrapper with `--env=SANE_CONFIG_DIR=/var/config/:`
